# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-updates:
        applies-to: version-updates
        update-types: [minor, patch]
      major-updates:
        applies-to: version-updates
        update-types: [major]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
